#!/bin/bash
# B端测试环境设置脚本

echo "========================================="
echo "🔧 B端测试环境设置向导"
echo "========================================="
echo ""
echo "请按照以下步骤操作:"
echo ""
echo "步骤1: 获取A端分享参数"
echo "----------------------------------------"
echo "1. 打开微信开发者工具"
echo "2. 运行项目(A端)"
echo "3. 登录并创建聊天"
echo "4. 点击分享,在Console中查看分享参数"
echo ""
echo "示例分享参数:"
echo "  chatId=chat_1759821214735_ikyy8g9u6"
echo "  inviter=向冬"
echo "  fromInvite=true"
echo ""
read -p "请输入chatId: " CHAT_ID
read -p "请输入inviter(邀请者昵称): " INVITER
echo ""
echo "========================================="
echo "步骤2: 配置B端编译模式"
echo "========================================="
echo ""
echo "在微信开发者工具中:"
echo "1. 点击顶部'编译' → '添加编译模式'"
echo "2. 填写以下信息:"
echo ""
echo "   模式名称: B端测试"
echo "   启动页面: app/pages/login/login"
echo "   启动参数:"
echo ""
ENCODED_INVITER=$(python3 -c "import urllib.parse; print(urllib.parse.quote('$INVITER'))")
echo "scene=1001&inviter=${ENCODED_INVITER}&chatId=${CHAT_ID}&fromInvite=true"
echo ""
echo "3. 点击'确定'保存"
echo "4. 选择'B端测试'编译模式"
echo "5. 点击'编译'"
echo "6. 使用不同的账号登录(不要用A端的账号!)"
echo ""
echo "========================================="
echo "步骤3: 验证B端身份"
echo "========================================="
echo ""
echo "在Console中搜索以下内容:"
echo ""
echo "✅ 应该看到:"
echo "  - isFromInvite: true"
echo "  - isSender: false"
echo "  - [B端系统消息] 加入${INVITER}的聊天"
echo ""
echo "❌ 不应该看到:"
echo "  - [a端系统消息] 您创建了私密聊天"
echo "  - isSender: true"
echo ""
echo "========================================="
echo "步骤4: 复制B端日志"
echo "========================================="
echo ""
echo "1. 在Console面板中,右键点击日志区域"
echo "2. 选择'全选' 或 Cmd+A"
echo "3. 复制日志 Cmd+C"
echo "4. 粘贴到聊天窗口提供给我"
echo ""
echo "========================================="
echo "✅ 设置完成!"
echo "========================================="

